# Generated by Django 5.2.5 on 2026-05-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
